name: "Cloud Run: get service URL"
description: "Fetches the public URL of a Cloud Run service."

inputs:
  service-name:
    description: "Cloud Run service name"
    required: true
  region:
    description: "GCP region"
    required: true
  project-id:
    description: "GCP project id"
    required: true

outputs:
  service-url:
    description: "Resolved service URL"
    value: ${{ steps.url.outputs.service_url }}

runs:
  using: "composite"
  steps:
    - name: Read URL
      id: url
      shell: bash
      run: |
        SERVICE_URL=$(gcloud run services describe "${{ inputs.service-name }}" \
          --region="${{ inputs.region }}" \
          --project="${{ inputs.project-id }}" \
          --format='value(status.url)')
        echo "service_url=${SERVICE_URL}" >> "$GITHUB_OUTPUT"

