name: "Docker: promote image"
description: "Pulls an image, retags it, and pushes the new tag (typical dev -> prod promotion)."

inputs:
  source-image:
    description: "Full source image (including tag)"
    required: true
  target-image:
    description: "Full target image (including tag)"
    required: true

runs:
  using: "composite"
  steps:
    - name: Pull source image
      shell: bash
      run: docker pull "${{ inputs.source-image }}"

    - name: Retag
      shell: bash
      run: docker tag "${{ inputs.source-image }}" "${{ inputs.target-image }}"

    - name: Push target image
      shell: bash
      run: docker push "${{ inputs.target-image }}"

