name: "Cloud Run: deploy"
description: "Deploy an image to an existing Cloud Run service."

inputs:
  service-name:
    description: "Cloud Run service name"
    required: true
  image:
    description: "Container image (including tag)"
    required: true
  region:
    description: "GCP region"
    required: true
  project-id:
    description: "GCP project id"
    required: true

runs:
  using: "composite"
  steps:
    - name: Deploy
      shell: bash
      run: |
        gcloud run services update "${{ inputs.service-name }}" \
          --image="${{ inputs.image }}" \
          --region="${{ inputs.region }}" \
          --project="${{ inputs.project-id }}"

