name: GCP auth (WIF) + gcloud
description: "Authenticates to Google Cloud using Workload Identity Federation and installs gcloud/gsutil."

inputs:
  workload-identity-provider:
    description: "WIF provider resource name"
    required: true
  service-account:
    description: "Service account email"
    required: true

runs:
  using: "composite"
  steps:
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: ${{ inputs.workload-identity-provider }}
        service_account: ${{ inputs.service-account }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

