name: "GCS: rsync"
description: "Sync a local directory to a GCS bucket path."

inputs:
  source:
    description: "Local directory to sync"
    required: true
  bucket:
    description: "Bucket name (without gs://)"
    required: true

runs:
  using: "composite"
  steps:
    - name: Sync to GCS
      shell: bash
      run: gsutil -m rsync -r -d "${{ inputs.source }}" "gs://${{ inputs.bucket }}/"

