name: "Pipeline: Cloud Run service (dev)"
description: "Runs tests, builds+pushes an image, syncs static assets, deploys to Cloud Run, then smoke-tests the live URL."

inputs:
  # Identity / project wiring
  workload-identity-provider:
    description: "WIF provider resource name"
    required: true
  service-account:
    description: "GCP service account email"
    required: true
  region:
    description: "GCP region (Cloud Run + Artifact Registry hostname)"
    required: true
  project-id:
    description: "GCP project id"
    required: true

  # Service + registry config
  service-name:
    description: "Cloud Run service name"
    required: true
  docker-repo:
    description: "Artifact Registry repository name"
    required: true

  # Build inputs
  docker-context:
    description: "Docker build context"
    required: false
    default: "."
  dockerfile:
    description: "Dockerfile path"
    required: false
    default: "Dockerfile"

  # Static assets
  static-bucket:
    description: "GCS bucket for static assets"
    required: true
  static-source:
    description: "Local directory with static assets"
    required: false
    default: "public/static"

  # Tests
  run-tests:
    description: "Location of where to run the tests"
    required: false
    default: "true"
  php-working-directory:
    description: "Where composer.json lives"
    required: false
    default: "."
  php-version:
    description: "PHP version"
    required: false
    default: "8.2"

  # Smoke test
  smoke-path:
    description: "Path to append when checking the service"
    required: false
    default: ""
  smoke-expected:
    description: "Text expected in the response body"
    required: false
    default: "PHP-FPM on Cloud Run"

outputs:
  image:
    description: "Image that was deployed"
    value: ${{ steps.meta.outputs.image }}
  service-url:
    description: "Resolved Cloud Run service URL"
    value: ${{ steps.url.outputs.service-url }}

runs:
  using: "composite"
  steps:
    - name: Compute image tag
      id: meta
      shell: bash
      run: |
        BRANCH_NAME="${GITHUB_REF_NAME//\//-}"
        SHORT_SHA="${GITHUB_SHA::7}"
        IMAGE_TAG="${BRANCH_NAME}-${SHORT_SHA}"
        IMAGE="${{ inputs.region }}-docker.pkg.dev/${{ inputs.project-id }}/${{ inputs.docker-repo }}/${{ inputs.service-name }}:${IMAGE_TAG}"
        echo "IMAGE_TAG=${IMAGE_TAG}" >> "$GITHUB_ENV"
        echo "IMAGE=${IMAGE}" >> "$GITHUB_ENV"
        echo "image=${IMAGE}" >> "$GITHUB_OUTPUT"

    - name: PHP tests
      if: inputs.run-tests == 'true'
      uses: ./.github/actions/php-tests
      with:
        php-version: ${{ inputs.php-version }}
        working-directory: ${{ inputs.php-working-directory }}

    - name: GCP auth + tooling
      uses: ./.github/actions/gcp-auth-setup
      with:
        workload-identity-provider: ${{ inputs.workload-identity-provider }}
        service-account: ${{ inputs.service-account }}
        region: ${{ inputs.region }}

    - name: Build and push image
      uses: ./.github/actions/docker-build-push
      with:
        image: ${{ steps.meta.outputs.image }}
        context: ${{ inputs.docker-context }}
        dockerfile: ${{ inputs.dockerfile }}

    - name: Upload static assets
      uses: ./.github/actions/gcs-sync
      with:
        source: ${{ inputs.static-source }}
        bucket: ${{ inputs.static-bucket }}

    - name: Deploy to Cloud Run
      uses: ./.github/actions/cloudrun-deploy
      with:
        service-name: ${{ inputs.service-name }}
        image: ${{ steps.meta.outputs.image }}
        region: ${{ inputs.region }}
        project-id: ${{ inputs.project-id }}

    - name: Get service URL
      id: url
      uses: ./.github/actions/cloudrun-get-url
      with:
        service-name: ${{ inputs.service-name }}
        region: ${{ inputs.region }}
        project-id: ${{ inputs.project-id }}

    - name: Post-deploy smoke test
      uses: ./.github/actions/http-smoke-test
      with:
        url: ${{ steps.url.outputs.service-url }}
        path: ${{ inputs.smoke-path }}
        expected: ${{ inputs.smoke-expected }}

