name: "GCP: auth + gcloud + docker auth"
description: "Authenticates via WIF, installs gcloud, and configures docker for Artifact Registry."

inputs:
  workload-identity-provider:
    description: "WIF provider resource name"
    required: true
  service-account:
    description: "GCP service account email"
    required: true
  region:
    description: "Artifact Registry region (e.g. europe-west3)"
    required: true

runs:
  using: "composite"
  steps:
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: ${{ inputs.workload-identity-provider }}
        service_account: ${{ inputs.service-account }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Configure Docker for Artifact Registry
      shell: bash
      run: gcloud auth configure-docker ${{ inputs.region }}-docker.pkg.dev --quiet

