name: "Pipeline: Cloud Run service (prod promote)"
description: "Promotes an image from dev to prod, syncs static assets, deploys to Cloud Run, health check"

inputs:
  workload-identity-provider:
    description: "WIF provider resource name"
    required: true
  service-account:
    description: "GCP service account email"
    required: true
  region:
    description: "GCP region"
    required: true

  dev-project-id:
    description: "Source GCP project (dev)"
    required: true
  prod-project-id:
    description: "Target GCP project (prod)"
    required: true
  docker-repo:
    description: "Artifact Registry repository name"
    required: true
  service-name:
    description: "Cloud Run image name"
    required: true

  source-tag:
    description: "Tag from dev to promote (e.g. main-sha1234)"
    required: true
  target-tag:
    description: "Prod tag to push/deploy (e.g. v1.2.3)"
    required: true

  static-bucket:
    description: "GCS bucket for static assets (no gs:// prefix)"
    required: true
  static-source:
    description: "Local directory with static assets"
    required: false
    default: "public/static"

  smoke-path:
    description: "Path to append when checking the service (e.g. /healthz)"
    required: false
    default: ""
  smoke-expected:
    description: "Text expected in the response body"
    required: false
    default: "PHP-FPM on Cloud Run"

outputs:
  image:
    description: "Image that was deployed"
    value: ${{ steps.meta.outputs.target_image }}
  service-url:
    description: "Resolved Cloud Run service URL"
    value: ${{ steps.url.outputs.service-url }}

runs:
  using: "composite"
  steps:
    - name: Compute source/target images
      id: meta
      shell: bash
      run: |
        SOURCE_IMAGE="${{ inputs.region }}-docker.pkg.dev/${{ inputs.dev-project-id }}/${{ inputs.docker-repo }}/${{ inputs.service-name }}:${{ inputs.source-tag }}"
        TARGET_IMAGE="${{ inputs.region }}-docker.pkg.dev/${{ inputs.prod-project-id }}/${{ inputs.docker-repo }}/${{ inputs.service-name }}:${{ inputs.target-tag }}"
        echo "source_image=${SOURCE_IMAGE}" >> "$GITHUB_OUTPUT"
        echo "target_image=${TARGET_IMAGE}" >> "$GITHUB_OUTPUT"

    - name: GCP auth + tooling
      uses: ./.github/actions/gcp-auth-setup
      with:
        workload-identity-provider: ${{ inputs.workload-identity-provider }}
        service-account: ${{ inputs.service-account }}
        region: ${{ inputs.region }}

    - name: Promote image (dev -> prod)
      uses: ./.github/actions/docker-promote-image
      with:
        source-image: ${{ steps.meta.outputs.source_image }}
        target-image: ${{ steps.meta.outputs.target_image }}

    - name: Upload static assets
      uses: ./.github/actions/gcs-sync
      with:
        source: ${{ inputs.static-source }}
        bucket: ${{ inputs.static-bucket }}

    - name: Deploy to Cloud Run
      uses: ./.github/actions/cloudrun-deploy
      with:
        service-name: ${{ inputs.service-name }}
        image: ${{ steps.meta.outputs.target_image }}
        region: ${{ inputs.region }}
        project-id: ${{ inputs.prod-project-id }}

    - name: Get service URL
      id: url
      uses: ./.github/actions/cloudrun-get-url
      with:
        service-name: ${{ inputs.service-name }}
        region: ${{ inputs.region }}
        project-id: ${{ inputs.prod-project-id }}

    - name: Post-deploy smoke test
      uses: ./.github/actions/http-smoke-test
      with:
        url: ${{ steps.url.outputs.service-url }}
        path: ${{ inputs.smoke-path }}
        expected: ${{ inputs.smoke-expected }}


